# Generated by Django 3.1.8 on 2021-04-18 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_nationalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalid',
            name='birth',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='birthday'),
            preserve_default=False,
        ),
    ]
