# Generated by Django 3.1.8 on 2021-04-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_nationalid_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalid',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
